title: Flutter
url: https://docs.flutter.dev
main-url: https://flutter.dev
email: flutter-dev@googlegroups.com

google_analytics_id: UA-67589403-1
google_site_verification: HFqxhSbf9YA_0rBglNLzDiWnrHiK_w4cqDh2YD2GEY4
google_tag_manager_id: GTM-ND4LWWZ
default_share_image: /assets/images/flutter-logo-sharing.png


github_username: flutter
branch: main
repo:
  organization: https://github.com/flutter
  this: https://github.com/flutter/website
  flutter: https://github.com/flutter/flutter
  samples: https://github.com/flutter/samples
  packages: https://github.com/flutter/packages
  gallery-archive: https://github.com/flutter/gallery
  engine: https://github.com/flutter/engine
  uxr: https://github.com/flutter/uxr
  wonderous: https://github.com/gskinnerTeam/flutter-wonderous-app
dart:
  api: https://api.dart.dev
  sdk:
    channel: stable
sdk:
  channel: stable # When changing this value also update it in src/_assets/js/archive.js
social:
  twitter: https://twitter.com/FlutterDev
  youtube: https://www.youtube.com/@flutterdev
dart-site: https://dart.dev
news: https://news.dartlang.org
api: https://api.flutter.dev
main-api: https://main-api.flutter.dev
pub: https://pub.dev
pub-api: https://pub.dev/documentation
pub-pkg: https://pub.dev/packages
flutter-medium: https://medium.com/flutter
medium: https://medium.com
dartpad: https://dartpad.dev
gallery-archive: https://flutter-gallery-archive.web.app
material: https://m3.material.io
material2: https://m2.material.io
so: https://stackoverflow.com
github: https://github.com
flutter-assets: https://flutter.github.io/assets-for-api-docs/assets
android-dev: https://developer.android.com
apple-dev: https://developer.apple.com
google-blog: https://developers.googleblog.com
developers: https://developers.google.com
codelabs: https://codelabs.developers.google.com
groups: https://groups.google.com
firebase: https://firebase.google.com
wonderous: https://wonderous.app/
youtube-site: https://youtube.com

yt:
  set: 'frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen loading="lazy"'
  set-short: 'frameborder="0" allowfullscreen loading="lazy"'
  watch: 'https://www.youtube.com/watch'
  embed: 'https://www.youtube.com/embed'
  playlist: 'https://www.youtube.com/playlist?list='

## Software minimum versions

appmin:
  git_win: 2.27
  git_mac: 2.27
  vscode: 1.77
  android_studio: '2023.2 (Iguana)'
  intellij_idea: '2023.2'
  android_sdk: 21
  powershell: 5.0
  xcode: '14'
  ios: '17'
  cocoapods: '1.10'
devmin:
  windows: '64-bit version of Microsoft Windows 10'
  macos: '10.15 (Catalina)'
  linux:
    debian: 11
    ubuntu: '20.04 LTS'
targetmin:
  windows: 'Microsoft Windows 7'
  macos: '10.14 (Ventura)'
  linux:
    debian: 10
    ubuntu: '18.04 LTS'
  ios: 12
  android: 'Android API level 21'

## Software current versions

appnow:
  flutter: '3.19.5'
  vscode: '1.88'
  android_studio: '2023.12 (Iguana) or later'
  android_sdk: '34.0.0'
  intellij: '2024.1'
  powershell: 5.1
  xcode: '15'
  ios: '17'
  cocoapods: '1.13'
